### ISSUE TITLE
Switch credential loading to use dotenv library

### ISSUE THREAD

**Issue by Maria-Cordero** [class-Track/backend#24]
dotenv library is already installed, we currently put the credentials directly when creating the psycopg2 connection. We need to change to using the dotenv library to load them directly from the db_access.env file. 

* (Once it works, add the file to the git ignore )

**Comment by igtampe** [comment]
Remember, Heroku has an environment variable already defined for the DBURL. It's called `DATABASE_URL`

We really should be primarily using that to load credentials, but si algo we can also have a fallback for local testing with this. It's what I do with my own APIs

**Comment by igtampe** [comment]
The URL takes some parsing to get everything from. Ideally the format it's stored as in `DATABASE_URL` is the format we'd use for the environment file to make getting and updating it easier. I had provided this small python method from another project we worked on. Will add it here for easy access again


```py
import os

puri = os.environ.get('DATABASE_URL','(default URL)')
filler, credentials = puri.split("postgres://")
slice1, slice2 = credentials.split("@")
username, password = slice1.split(":")
host, slice3 = slice2.split(":")
port, database = slice3.split("/")

aiem_config = {
    'dbname': database,
    'user': username,
    'host': host,
    'password': password,
    'port': port
}
```
